import { readdir, writeFile, readFile, mkdir } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { defaultDefs } from './components.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = join(__dirname, '..');
const diagramsDir = join(__dirname, 'diagrams');

// Parse CLI args
const args = process.argv.slice(2);
let onlyFilter = null;
const onlyIdx = args.indexOf('--only');
if (onlyIdx !== -1 && args[onlyIdx + 1]) {
  onlyFilter = args[onlyIdx + 1];
}

/**
 * Wrap SVG content into a full SVG document
 */
function buildSvg(viewBox, body) {
  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}" width="${viewBox.split(' ')[2]}" height="${viewBox.split(' ')[3]}">
${defaultDefs()}
${body}
</svg>`;
}

/**
 * Ensure directory exists
 */
async function ensureDir(dir) {
  await mkdir(dir, { recursive: true });
}

/**
 * Sanitize SVG text content: escape unescaped & in text nodes
 * This fixes legacy SVG files that were generated without proper XML escaping
 */
function sanitizeSvgContent(svg) {
  // Match & that is NOT followed by amp; lt; gt; quot; apos; #(decimal); #x(hex);
  return svg.replace(/&(?!amp;|lt;|gt;|quot;|apos;|#\d+;|#x[0-9a-fA-F]+;)/g, '&amp;');
}

/**
 * Sanitize all existing SVG files in output directories
 */
async function sanitizeLegacySvgs() {
  const outputDirs = [
    join(rootDir, 'zh', 'assets', 'images'),
    join(rootDir, 'en', 'assets', 'images'),
  ];

  let fixed = 0;
  for (const dir of outputDirs) {
    let files;
    try {
      files = (await readdir(dir)).filter(f => f.endsWith('.svg'));
    } catch {
      continue;
    }
    for (const file of files) {
      const filePath = join(dir, file);
      const content = await readFile(filePath, 'utf-8');
      const sanitized = sanitizeSvgContent(content);
      if (sanitized !== content) {
        await writeFile(filePath, sanitized, 'utf-8');
        console.log(`  🔧 Fixed XML escaping: ${file} (${dir.includes('zh') ? 'zh' : 'en'})`);
        fixed++;
      }
    }
  }
  return fixed;
}

/**
 * Main generation
 */
async function main() {
  console.log('🎨 SVG Illustration Generator');
  console.log('─'.repeat(40));

  // Discover diagram modules
  let files;
  try {
    files = (await readdir(diagramsDir)).filter(f => f.endsWith('.mjs'));
  } catch (e) {
    console.error(`❌ Cannot read diagrams directory: ${diagramsDir}`);
    process.exit(1);
  }

  if (files.length === 0) {
    console.log('⚠️  No diagram files found in diagrams/');
    return;
  }

  console.log(`📂 Found ${files.length} diagram module(s)\n`);

  let generated = 0;
  let skipped = 0;

  for (const file of files) {
    const modulePath = `./diagrams/${file}`;
    const mod = await import(modulePath);
    const diagrams = mod.diagrams || (mod.default ? [mod.default] : []);

    for (const diagram of diagrams) {
      const { filename, viewBox, render } = diagram;

      if (!filename || !viewBox || !render) {
        console.warn(`  ⚠️  Skipping invalid diagram in ${file}`);
        skipped++;
        continue;
      }

      if (onlyFilter && filename !== onlyFilter) {
        skipped++;
        continue;
      }

      console.log(`  ⏳ Generating: ${filename}`);

      const body = render();
      const svg = buildSvg(viewBox, body);

      // Output to both zh and en asset directories
      const targets = [
        join(rootDir, 'zh', 'assets', 'images', `${filename}.svg`),
        join(rootDir, 'en', 'assets', 'images', `${filename}.svg`),
      ];

      for (const target of targets) {
        await ensureDir(dirname(target));
        await writeFile(target, svg, 'utf-8');
      }

      console.log(`  ✅ ${filename}.svg → zh/ & en/`);
      generated++;
    }
  }

  console.log('\n' + '─'.repeat(40));
  console.log(`✨ Done! Generated: ${generated}, Skipped: ${skipped}`);

  // Sanitize all SVG files (including legacy ones not generated by this script)
  console.log('\n🔍 Checking all SVG files for XML escaping issues...');
  const fixed = await sanitizeLegacySvgs();
  if (fixed > 0) {
    console.log(`  📝 Fixed ${fixed} file(s) with XML escaping issues`);
  } else {
    console.log('  ✅ All SVG files have proper XML escaping');
  }
}

main().catch(err => {
  console.error('❌ Generation failed:', err);
  process.exit(1);
});
